sudo: false
language: node_js
cache: npm
notifications:
  email: false
node_js:
  - "10"
script:
  - echo NO TESTS
deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/travis_after_success.sh
  on:
    all_branches: true
branches:
  only:
   - develop
